import { getAIProvider, AI_MODELS, estimateCost } from "./router";
import { logAiUsage } from "./usage-logger";
import { TextMessage } from "./provider";

export interface GeneratedQuestion {
  question_type: "mcq" | "open_ended";
  question_text: string;
  concept_name: string;
  options: string[];
  correct_answer: string;
  difficulty: number;
  explanation: string;
  hint: string;
  source_page?: number | null;
}

export interface GenerateQuizParams {
  userId: string;
  projectId: string;
  materialId?: string;
  materialName?: string;
  questionCount: number;
  difficultyInstructions: string;
  contextStr: string;
  recentQuestionTexts?: string[];
  availableConcepts?: Array<{ id: string; name: string }>;
}

const QUIZ_SCHEMA = {
  type: "object",
  properties: {
    questions: {
      type: "array",
      items: {
        type: "object",
        properties: {
          question_type: { type: "string", enum: ["mcq", "open_ended"] },
          question_text: { type: "string" },
          concept_name: {
            type: "string",
            description: "Concept tested by this question (must match an available material concept if provided)",
          },
          options: {
            type: "array",
            items: { type: "string" },
            description: "Exactly 4 distinct, plausible options for MCQ; empty array [] for open_ended",
          },
          correct_answer: {
            type: "string",
            description: "For MCQ, the exact text of the correct option; for open_ended, an exemplary model answer",
          },
          difficulty: { type: "number", minimum: 1, maximum: 5 },
          explanation: {
            type: "string",
            description: "Clear explanation grounded directly in the study material",
          },
          hint: {
            type: "string",
            description: "Pedagogical hint guiding the student without giving away the answer",
          },
          source_page: {
            type: "number",
            description: "Page number from the study material context where this fact is found",
          },
        },
        required: [
          "question_type",
          "question_text",
          "concept_name",
          "correct_answer",
          "difficulty",
          "options",
          "explanation",
          "hint",
        ],
      },
    },
  },
  required: ["questions"],
};

/**
 * Validate and clean questions generated by Gemini.
 */
export function validateQuestions(rawQuestions: unknown[]): GeneratedQuestion[] {
  const valid: GeneratedQuestion[] = [];

  for (const item of rawQuestions) {
    if (!item || typeof item !== "object") continue;
    const q = item as Record<string, unknown>;

    const type = q.question_type === "open_ended" ? "open_ended" : "mcq";
    const text = typeof q.question_text === "string" ? q.question_text.trim() : "";
    const concept = typeof q.concept_name === "string" ? q.concept_name.trim() : "";
    const answer = typeof q.correct_answer === "string" ? q.correct_answer.trim() : "";
    const diff = typeof q.difficulty === "number" && q.difficulty >= 1 && q.difficulty <= 5 ? Math.round(q.difficulty) : 3;
    const explanation = typeof q.explanation === "string" ? q.explanation.trim() : "Grounded in study material.";
    const hint = typeof q.hint === "string" ? q.hint.trim() : "Think about the key principles covered in this section.";
    const page = typeof q.source_page === "number" ? q.source_page : null;

    if (!text || !answer) continue;

    if (type === "mcq") {
      const rawOptions = Array.isArray(q.options)
        ? q.options.map((o) => (typeof o === "string" ? o.trim() : "")).filter(Boolean)
        : [];

      // Deduplicate options
      const uniqueOptions = [...new Set(rawOptions)];
      if (uniqueOptions.length !== 4) continue; // MCQs must have exactly 4 unique options

      // Ensure correct_answer matches one of the 4 options or is a valid letter (A, B, C, D)
      let resolvedAnswer = answer;
      const letters = ["A", "B", "C", "D"];
      const letterIdx = letters.indexOf(answer.toUpperCase());
      if (letterIdx >= 0 && letterIdx < uniqueOptions.length) {
        resolvedAnswer = uniqueOptions[letterIdx];
      } else if (!uniqueOptions.some((opt) => opt.toLowerCase() === answer.toLowerCase())) {
        // Correct answer does not match any option
        continue;
      }

      valid.push({
        question_type: "mcq",
        question_text: text,
        concept_name: concept,
        options: uniqueOptions,
        correct_answer: resolvedAnswer,
        difficulty: diff,
        explanation,
        hint,
        source_page: page,
      });
    } else {
      valid.push({
        question_type: "open_ended",
        question_text: text,
        concept_name: concept,
        options: [],
        correct_answer: answer,
        difficulty: diff,
        explanation,
        hint,
        source_page: page,
      });
    }
  }

  return valid;
}

/**
 * Generate adaptive quiz questions using Gemini structured output.
 */
export async function generateQuizQuestions(
  params: GenerateQuizParams
): Promise<GeneratedQuestion[]> {
  const provider = getAIProvider();
  const start = Date.now();

  const systemInstruction = `You are an expert adaptive quiz generator for an educational platform.
Generate exactly ${params.questionCount} high-quality, rigorous assessment questions grounded EXCLUSIVELY in the provided study material.

GROUNDING & INTEGRITY RULES:
1. STRICT GROUNDING: Every question and answer MUST be directly verifiable from the STUDY MATERIAL below.
2. NO EXTERNAL OR PRD KNOWLEDGE: Do NOT use general world knowledge. NEVER create questions about product architecture, Spaces, Projects, Admin, or software tools unless that is literally the topic of the study material itself.
3. CONCEPTS & DIFFICULTY: Test the requested concepts at their assigned difficulty levels (1=foundational to 5=advanced analysis).
4. MCQ FORMAT:
   - Exactly 4 plausible, distinct options.
   - Exactly ONE unambiguously correct answer.
   - Three high-quality distractors from the same conceptual domain (no silly or obviously wrong options).
   - No duplicate options, no "All of the above", no "None of the above".
5. OPEN-ENDED FORMAT: Provide a comprehensive, clear model answer covering the key points.
6. EXPLANATION & HINTS:
   - Provide a clear explanation citing facts from the text.
   - Provide a helpful pedagogical hint that guides thinking without giving away the answer.
   - Include the source page number from the text if available.`;

  const candidateConceptNames = (params.availableConcepts ?? [])
    .map((c) => c.name.trim())
    .filter(Boolean);

  const conceptInstruction =
    candidateConceptNames.length > 0
      ? `\nMANDATORY CONCEPT SELECTION:
For each generated question, the "concept_name" field MUST match one of the following explicit concepts:
${candidateConceptNames.map((c) => `- "${c}"`).join("\n")}
Do not invent unrelated concept names.\n`
      : "";

  const messages: TextMessage[] = [
    {
      role: "user",
      content: `TARGET CONCEPTS & ADAPTIVE DIFFICULTIES:
${params.difficultyInstructions}
${conceptInstruction}${
  params.recentQuestionTexts && params.recentQuestionTexts.length > 0
    ? `\nPREVIOUSLY ASKED QUESTIONS (DO NOT DUPLICATE OR REPEAT):
${params.recentQuestionTexts.slice(0, 8).map((q) => `- ${q}`).join("\n")}
Ensure the new questions explore different aspects, alternative scenarios, or deeper nuances of the concepts rather than repeating the same phrasing.\n`
    : ""
}
STUDY MATERIAL CONTEXT (${params.materialName ?? "Document"}):
${params.contextStr}

Generate ${params.questionCount} grounded quiz questions adhering strictly to the schema.`,
    },
  ];

  try {
    const result = await provider.generateStructured<{ questions: GeneratedQuestion[] }>({
      model: AI_MODELS.fast,
      systemInstruction,
      messages,
      schema: QUIZ_SCHEMA,
      temperature: 0.4,
      maxTokens: 3500,
    });

    const latencyMs = Date.now() - start;
    await logAiUsage({
      userId: params.userId,
      projectId: params.projectId,
      feature: "quiz_generation",
      model: AI_MODELS.fast,
      latencyMs,
      inputTokens: result.usage.inputTokens,
      outputTokens: result.usage.outputTokens,
      estimatedCostUsd: estimateCost(
        AI_MODELS.fast,
        result.usage.inputTokens,
        result.usage.outputTokens
      ),
      status: "success",
    });

    const raw = result.data?.questions ?? [];
    return validateQuestions(raw);
  } catch (error) {
    await logAiUsage({
      userId: params.userId,
      projectId: params.projectId,
      feature: "quiz_generation",
      model: AI_MODELS.fast,
      latencyMs: Date.now() - start,
      inputTokens: 0,
      outputTokens: 0,
      estimatedCostUsd: 0,
      status: "error",
      error: error instanceof Error ? error.message : String(error),
    });
    throw error;
  }
}
